### ISSUE TITLE
建议增加RGB颜色值的复制，还有那个……RGB色条太窄了，值显示不完全，看着很困扰

### ISSUE THREAD

**Issue by mllt992** [imoyao/GUSCSS#7]
is:issue is:open 建议增加RGB颜色值的复制，还有那个……RGB色条太窄了，值显示不完全，看着很困扰

![image](https://user-images.githubusercontent.com/59815753/190995114-0cfda022-e89e-4a46-9c29-f54c45aa574d.png)

**Comment by imoyao** [comment]
RGB颜色复制暂时不会加，链接中的`colorId`自己手动修改一下就可以，如果觉得麻烦，也可以复制16进制用相关工具或者使用js自己处理一下。
关于进度条显示的问题，已经做了相应的调整。
